version: 1.0.0.{build}

environment:
  configuration: Release
  node_version: "9"

branches:
  except:
  - design

image: Visual Studio 2017

init:
- ps: |
    Install-Product node $env:node_version

cache:
- '%USERPROFILE%\.nuget\packages -> **\*.csproj'
- '%LOCALAPPDATA%\npm-cache -> **\package.json'          # npm cache
- 'node_modules -> **\package.json'                      # local npm modules

before_build:
- ps: |
    appveyor-retry dotnet restore .\src\Payments.Mvc\
    appveyor-retry dotnet restore .\src\Payments.Jobs.MoneyMovement\

build_script:
- ps: |
    dotnet build .\src\Payments.Mvc\ --configuration $Env:configuration
    dotnet build .\src\Payments.Jobs.MoneyMovement\ --configuration $Env:configuration

after_build:
- ps: |
    dotnet publish .\src\Payments.Mvc\ --output ..\..\publish\Payments.Mvc --configuration $Env:configuration
    octo pack --id Payments.Mvc --version $Env:APPVEYOR_BUILD_VERSION --releaseNotes $Env:APPVEYOR_REPO_COMMIT_MESSAGE --basepath .\publish\Payments.Mvc\ --outFolder .\artifacts\

    dotnet publish .\src\Payments.Jobs.MoneyMovement\ --output ..\..\publish\Payments.Jobs.MoneyMovement --configuration $Env:configuration --runtime win-x64
    octo pack --id Payments.Jobs.MoneyMovement --version $Env:APPVEYOR_BUILD_VERSION --releaseNotes $Env:APPVEYOR_REPO_COMMIT_MESSAGE --basepath .\publish\Payments.Jobs.MoneyMovement\ --outFolder .\artifacts\

test_script:
- ps: dotnet test .\tests\Payments.Tests\Payments.Tests.csproj

artifacts:
- path: artifacts\**\*.nupkg
  name: nugetweb

deploy:
- provider: Octopus
  push_packages: true
  server: https://scruffy.caes.ucdavis.edu
  api_key:
    secure: 0bPmdZ5IVKjvNHKPjW4pNSmM223U0YV/oQKJ/NdN/CE=
  on:
    branch: master

notifications:
- provider: Slack
  incoming_webhook: https://hooks.slack.com/services/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
  channel: caes-development
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: false
