# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
  - master

pool:
  vmImage: "ubuntu-latest"

variables:
  solution: "**/*.sln"
  buildPlatform: "Any CPU"
  buildConfiguration: "Release"

stages:
  - stage: Test
    jobs:
      - job:
        steps:
          - task: UseDotNet@2
            displayName: "Use .NET 6 sdk"
            inputs:
              packageType: "sdk"
              version: 6.x

          - task: NodeTool@0
            displayName: "Use Node 14 (LTS)"
            inputs:
              versionSpec: "14.x"

          - task: DotNetCoreCLI@2
            displayName: "Run Server Tests"
            inputs:
              command: "test"

  - stage: Publish
    jobs:
      - job:
        steps:
          - task: UseDotNet@2
            displayName: "Use .NET 6 sdk"
            inputs:
              packageType: "sdk"
              version: 6.x

          - task: NodeTool@0
            displayName: "Use Node 14 (LTS)"
            inputs:
              versionSpec: "14.x"

          - task: DotNetCoreCLI@2
            displayName: "Publish Payments.Mvc"
            inputs:
              command: "publish"
              publishWebProjects: true
              zipAfterPublish: false
              modifyOutputPath: false
              projects: "./src/Payments.Mvc/Payments.Mvc.csproj"
              arguments: "--configuration $(BuildConfiguration) --output $(Build.ArtifactStagingDirectory)/"

          - task: DotNetCoreCLI@2
            displayName: "Publish Payments.Jobs.MoneyMovement"
            inputs:
              command: "publish"
              publishWebProjects: false
              zipAfterPublish: false
              projects: "./src/Payments.Jobs.MoneyMovement/Payments.Jobs.MoneyMovement.csproj"
              arguments: "--configuration $(buildConfiguration) --runtime win-x64 --output $(Build.ArtifactStagingDirectory)/app_data/jobs/triggered"

          - task: PublishBuildArtifacts@1
            condition: eq(variables['Build.SourceBranch'], 'refs/heads/master')
            displayName: "Publish Build Artifacts for master branch builds"
            inputs:
              PathtoPublish: "$(Build.ArtifactStagingDirectory)"
              ArtifactName: "build"
              publishLocation: "Container"
