# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: NuGetCommand@2
  inputs:
    command: 'restore'
    restoreSolution: '**/*.sln'

- task: DotNetCoreCLI@2
  displayName: 'Build Payments.Mvc'
  inputs:
    command: 'build'
    projects: './src/payments.mvc/payments.mvc.csproj'
    arguments: '--configuration $(buildConfiguration)'

- task: DotNetCoreCLI@2
  displayName: 'Assemble Payments.Mvc'
  inputs:
    command: 'publish'
    publishWebProjects: true
    zipAfterPublish: false
    modifyOutputPath: false
    projects: './src/payments.mvc/payments.mvc.csproj'
    arguments: '--configuration $(buildConfiguration) --output $(build.artifactstagingdirectory)/'

- task: DotNetCoreCLI@2
  displayName: 'Assemble Payments.Jobs.MoneyMovement'
  inputs:
    command: 'publish'
    publishWebProjects: false
    zipAfterPublish: false
    projects: './src/payments.jobs.moneymovement/payments.jobs.moneymovement.csproj'
    arguments: '--configuration $(buildConfiguration) --runtime win-x64 --output $(Build.ArtifactStagingDirectory)/app_data/jobs/triggered'

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifacts'
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'build'
    publishLocation: 'Container'

- task: DotNetCoreCLI@2
  displayName: 'Test'
  inputs:
    command: 'test'
    projects: './tests/payments.tests/payments.tests.csproj'
